name: Release

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install
      - name: Build release
        run: npm run build
      - name: Compress
        run: npm run compress
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: coco-${{ github.ref }}.zip
          name: ${{ github.workflow }} ${{ github.ref }}
          body_path: .changelog/CHANGELOG-${{ github.ref }}.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
